version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Kumar@danicha123"
      ACCEPT_EULA: "Y"
      
  aspnetapi:
    build: .
    ports:
      - 5000:80
    depends_on:
      - sqlserver
